---
name: $(Build.DefinitionName)-$(date:yyyyMMdd)$(rev:.r)

trigger: none

# parameters are typed with defaults so they are correctly populated, you will get a choice in the GUI to edit these, but you should keep all changes as code.
parameters:

  - name: SHORTHAND_ENVIRONMENT_NAME
    default: uat
    displayName: "What is the shorthand name for this environment?"
    type: string
    values:
      - dev
      - poc
      - mvp
      - tst
      - uat
      - ppd
      - prd

  - name: SHORTHAND_PROJECT_NAME
    type: string
    default: "ldo"
    displayName: "Shorthand Project e.g. lbdo for libredevops"

  - name: SHORTHAND_LOCATION_NAME
    type: string
    default: "euw"
    displayName: "3 character location name, e.g., uks, ukw, euw"

  - name: TERRAFORM_PATH
    type: string
    default: "avd-image-packer-build/terraform"
    displayName: "What is the path to your terraform code?"

  - name: TERRAFORM_VERSION
    type: string
    default: "1.4.4"
    displayName: "Which version of Terraform should be installed?"

  - name: VARIABLE_GROUP_NAME
    type: string
    default: "svp-kv-ldo-euw-uat-mgt-01"
    displayName: "Enter the variable group which contains your authentication information"

# This variable sets up a condition in the template, if set to true, it will run terraform plan -destroy instead of the normal plan
  - name: TERRAFORM_DESTROY
    default: true
    displayName: "Check box to run a Destroy"
    type: boolean

  - name: TERRAFORM_PLAN_ONLY
    default: false
    displayName: "Check box to run plan ONLY and never run apply"
    type: boolean

  - name: CHECKOV_SKIP_TESTS
    type: string
    default: 'CKV2_AZURE_1,CKV2_AZURE_18,CKV_AZURE_23,CKV_AZURE_24,CKV2_AZURE_31,CKV_AZURE_33,CKV_AZURE_35,CKV_AZURE_59,CKV_AZURE_97,CKV_AZURE_190,CKV_AZURE_206'
    displayName: "CheckOV tests to skip if comment skips don't work.  All checks run if parameter is empty, empty by default"

  - name: ADD_CLIENT_IP_TO_NSG
    type: boolean
    default: true
    displayName: Whether your client IP should be added to NSG, if this is set to true, NSG_ID must also be set

  - name: NSG_ID
    type: string
    default: "/subscriptions/66d5a5a0-559c-4049-a1b0-7bfd981ed1c7/resourceGroups/rg-ldo-euw-uat-build/providers/Microsoft.Network/networkSecurityGroups/nsg-ldo-euw-uat-01"
    displayName: The ID of the NSG to add client IP to.

  - name: PACKER_PATH
    type: string
    default: "packer/windows/10"
    displayName: "What is the path to your packer code?"

  - name: PACKER_FILE_NAME
    type: string
    default: "packer.pkr.hcl"
    displayName: "What is the name of your packer file?"

  - name: IMAGE_GALLERY_RG_NAME
    type: string
    values:
      - "rg-ldo-euw-uat-build"
    default: "rg-ldo-euw-uat-build"

  - name: IMAGE_GALLERY_NAME
    type: string
    values:
      - "galldoeuwuat01"
    default: "galldoeuwuat01"

  - name: IMAGE_DEFINITION_NAME
    type: string
    values:
      - "ldo-avd-windows-10"
    default: "ldo-avd-windows-10"


# Declare variable group to pass variables to parameters, in this case, a libre-devops keyvault which is using a service principle for authentication
variables:
  - group: ${{ parameters.VARIABLE_GROUP_NAME }}

# Sets what repos need cloned, for example, a library repo for modules and a poly-repo for target code
resources:
  repositories:

  - repository: azure-naming-convention
    type: github
    endpoint: github_service_connection
    name: libre-devops/azure-naming-convention
    ref: main

  - repository: terraform-azdo-pipeline-template
    type: github
    endpoint: github_service_connection
    name: libre-devops/terraform-azdo-pipeline-template
    ref: main

  - repository: packer-azdo-pipeline-template
    type: github
    endpoint: github_service_connection
    name: libre-devops/packer-azdo-pipeline-template
    ref: main

# You may wish to use a separate or self-hosted agent per job, by default, all jobs will inherit stage agent
pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

# Sets stage so that multiple stages can be used if needed, as it stands, only 1 stage is expected and is thus passed as a parameter
stages:

  - stage: "${{ parameters.SHORTHAND_ENVIRONMENT_NAME }}_DeleteImage"
    displayName: "${{ parameters.SHORTHAND_ENVIRONMENT_NAME }} Delete Images Stage"
    jobs:
      - job: Terraform_Build
        workspace:
          clean: all
        pool:
          vmImage: 'ubuntu-latest'
        displayName: Delete Images
        steps:

          # Declare the repos needed from the resources list
          - checkout: self
          - checkout: azure-naming-convention

          - bash: |
              az login --service-principal -u $(SpokeSvpClientId) -p $(SpokeSvpClientSecret) --tenant $(SpokeTenantId) && \
              
              ImageVersionNumber=$(az sig image-version list \
              --gallery-name ${{ parameters.IMAGE_GALLERY_NAME }} \
              --resource-group ${{ parameters.IMAGE_GALLERY_RG_NAME }} \
              --gallery-image-definition ${{ parameters.IMAGE_DEFINITION_NAME }} \
              -o tsv \
              --query "[].name")
              
              for sigImage in $ImageVersionNumber
              do
              az sig image-version delete \
              --gallery-name ${{ parameters.IMAGE_GALLERY_NAME }} \
              --resource-group ${{ parameters.IMAGE_GALLERY_RG_NAME }} \
              --gallery-image-definition ${{ parameters.IMAGE_DEFINITION_NAME }} \
              --gallery-image-version ${sigImage}
              done
              
              az image delete \
              --resource-group ${{ parameters.IMAGE_GALLERY_RG_NAME }} \
              --name ${{ parameters.IMAGE_DEFINITION_NAME }}
            displayName: "Delete all gallery image versions and image resources"


  - stage: "${{ parameters.SHORTHAND_ENVIRONMENT_NAME }}_PreReq"
    dependsOn: "${{ parameters.SHORTHAND_ENVIRONMENT_NAME }}_DeleteImage"
    displayName: "${{ parameters.SHORTHAND_ENVIRONMENT_NAME }} PreReq Stage"
    jobs:
      - job: Terraform_Build
        workspace:
          clean: all
        pool:
          vmImage: 'ubuntu-latest'
        displayName: Terraform Build
        steps:

          # Declare the repos needed from the resources list
          - checkout: self
          - checkout: azure-naming-convention

          # Remotely fetch pipeline template, in this case, I am using one in my development repo.
          - template: /.azurepipelines/.templates/terraform-cicd-template.yml@terraform-azdo-pipeline-template
            parameters:
              SHORTHAND_PROJECT_NAME: ${{ parameters.SHORTHAND_PROJECT_NAME }} # Parameters entered in YAML
              SHORTHAND_ENVIRONMENT_NAME: ${{ parameters.SHORTHAND_ENVIRONMENT_NAME }}
              SHORTHAND_LOCATION_NAME: ${{ parameters.SHORTHAND_LOCATION_NAME }}
              TERRAFORM_PATH: "${{ parameters.TERRAFORM_PATH }}/0-pre-req"
              TERRAFORM_VERSION: ${{ parameters.TERRAFORM_VERSION }}
              TERRAFORM_DESTROY: ${{ parameters.TERRAFORM_DESTROY }}
              TERRAFORM_PLAN_ONLY: ${{ parameters.TERRAFORM_PLAN_ONLY }}
              TERRAFORM_STORAGE_RG_NAME: $(SpokeSaRgName) # Key Vault variable
              TERRAFORM_STORAGE_ACCOUNT_NAME: $(SpokeSaName)
              TERRAFORM_BLOB_CONTAINER_NAME: $(SpokeSaBlobContainerName)
              TERRAFORM_STORAGE_KEY: $(SpokeSaPrimaryKey)
              TERRAFORM_STATE_NAME: "ldo-win10-uat-pre-req.terraform.tfstate""
              TERRAFORM_WORKSPACE_NAME: ${{ parameters.SHORTHAND_ENVIRONMENT_NAME }}
              TERRAFORM_COMPLIANCE_PATH: "$(Build.SourcesDirectory)/azure-naming-convention/az-terraform-compliance-policy"
              AZURE_TARGET_CLIENT_ID: $(SpokeSvpClientId)
              AZURE_TARGET_CLIENT_SECRET: $(SpokeSvpClientSecret)
              AZURE_TARGET_TENANT_ID: $(SpokeTenantId)
              AZURE_TARGET_SUBSCRIPTION_ID: $(SpokeSubID)
              CHECKOV_SKIP_TESTS: ${{ parameters.CHECKOV_SKIP_TESTS }}


