name: 'Windows Packer Build'

# Allow run manually
on:
  workflow_dispatch:

jobs:
  azure-terraform-job:
    name: 'Windows Packer Build'
    runs-on: self-hosted
    environment: uat

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Libre DevOps - Run Packer for Azure - GitHub Action
        id: packer-build
        uses: libre-devops/azure-packer-gh-action@v1
        with:
          packer-template-path: "packer/windows/10/packer.pkr.hcl"
          packer-client-id: ${{ secrets.SpokeSvpClientId }}
          packer-client-secret: ${{ secrets.SpokeSvpClientSecret }}
          packer-subscription-id: ${{ secrets.SpokeSubId }}
          packer-tenant-id: ${{ secrets.SpokeTenantId }}
          packer-version: "latest"

