name: 'Packer Build'

# Allow run manually
on:
  workflow_dispatch:

jobs:
  azure-terraform-job:
    name: 'Terraform Build'
    runs-on: ubuntu-latest
    environment: tst

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - name: Packer GitHub Actions
        uses: hashicorp/packer-github-actions@v0.2.0
        with:
          command: build
          target: "packer/linux/ubuntu/2204/ubuntu2204.pkr.hcl"
        env:
          PKR_VAR_client_id: ${{ secrets.SpokeSvpClientId }}
          PKR_VAR_client_secret: ${{ secrets.SpokeSvpClientSecret }}
          PKR_VAR_subscription_id: ${{ secrets.SpokeSubId }}
          PKR_VAR_tenant_id: ${{ secrets.SpokeTenantId }}
          PKR_VAR_gallery_name: ${{ secrets.SpokeImageGalleryName }}
          PKR_VAR_gallery_rg_name: ${{ secrets.SpokeImageGalleryRgName }}
          PKR_VAR_dockerhub_login: ${{ secrets.DockerHubUsername }}
          PKR_VAR_dockerhub_password: ${{ secrets.DockerHubPassword }}
