name: "Pre-Req Terraform Destroy"

# Allow run manually
on:
  workflow_dispatch:

env:
  BUILD_DEFINITION_NAME: "Example"
  BUILD_DATE: "${{ github.run_id }}"
  REV: "r"

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - SHORTHAND_ENVIRONMENT_NAME: uat
            SHORTHAND_PROJECT_NAME: ldo
            SHORTHAND_LOCATION_NAME: euw
            ADD_CLIENT_IP_TO_NSG: true
            NSG_ID_SECRET: NSG_ID
            INSTALL_PASSWORD_SECRET: LocalLdoAdminUatPwd
            PACKER_PATH: "packer/windows/10"
            PACKER_FILE_NAME: "packer.pkr.hcl"
            IMAGE_GALLERY_RG_NAME: "rg-ldo-euw-uat-build"
            IMAGE_GALLERY_NAME: "galldoeuwuat01"
            IMAGE_DEFINITION_NAME: "ldo-avd-windows-10"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-cli pywinrm
        shell: pwsh

      - name: Remove any image versions from gallery
        run: |
          set -xe
          az login --service-principal -u ${ARM_CLIENT_ID} -p ${ARM_CLIENT_SECRET} --tenant ${ARM_TENANT_ID} && \

          ImageVersionNumber=$(az sig image-version list \
          --gallery-name ${IMAGE_GALLERY_NAME} \
          --resource-group ${IMAGE_GALLERY_RG_NAME} \
          --gallery-image-definition ${IMAGE_DEFINITION_NAME} \
          -o tsv \
          --query "[].name")

          for sigImage in $ImageVersionNumber
          do
          az sig image-version delete \
          --gallery-name ${IMAGE_GALLERY_NAME} \
          --resource-group ${IMAGE_GALLERY_RG_NAME} \
          --gallery-image-definition ${IMAGE_DEFINITION_NAME} \
          --gallery-image-version ${sigImage}
          done

          az image delete \
          --resource-group ${IMAGE_GALLERY_RG_NAME} \
          --name ${IMAGE_DEFINITION_NAME}

        env:
          ARM_CLIENT_ID: ${{ secrets.SpokeSvpClientId }}
          ARM_CLIENT_SECRET: ${{ secrets.SpokeSvpClientSecret }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SpokeSubId }}
          ARM_TENANT_ID: ${{ secrets.SpokeTenantId }}
          IMAGE_GALLERY_RG_NAME: ${{ matrix.IMAGE_GALLERY_RG_NAME }}
          IMAGE_GALLERY_NAME: ${{ matrix.IMAGE_GALLERY_NAME }}
          IMAGE_DEFINITION_NAME: ${{ matrix.IMAGE_DEFINITION_NAME }}
        shell: bash

      - name: Libre DevOps - Run Terraform for Azure - GitHub Action
        id: terraform-build
        uses: libre-devops/azure-terraform-gh-action@v1
        with:
          terraform-path: "terraform/0-pre-req"
          terraform-workspace-name: "uat"
          terraform-backend-storage-rg-name: ${{ secrets.SpokeSaRgName }}
          terraform-backend-storage-account-name: ${{ secrets.SpokeSaName }}
          terraform-backend-blob-container-name: ${{ secrets.SpokeSaBlobContainerName }}
          terraform-backend-storage-access-key: ${{ secrets.SpokeSaPrimaryKey }}
          terraform-backend-state-name: "ldo-win10-uat-pre-req.terraform.tfstate"
          terraform-provider-client-id: ${{ secrets.SpokeSvpClientId }}
          terraform-provider-client-secret: ${{ secrets.SpokeSvpClientSecret }}
          terraform-provider-subscription-id: ${{ secrets.SpokeSubId }}
          terraform-provider-tenant-id: ${{ secrets.SpokeTenantId }}
          terraform-compliance-path: "git:https://github.com/libre-devops/azure-naming-convention.git//?ref=main"
          checkov-skipped-tests: "CKV_AZURE_97,CKV_AZURE_116,CKV_AZURE_117,CKV_AZURE_137,CKV_AZURE_138,CKV_AZURE_139,CKV_AZURE_141,CKV_AZURE_145,CKV_AZURE_151,CKV_AZURE_33,CKV_AZURE_34,CKV_AZURE_35,CKV_AZURE_4,CKV_AZURE_44,CKV_AZURE_50,CKV_AZURE_7,CKV_AZURE_98,CKV2_AZURE_1,CKV2_AZURE_18,CKV2_AZURE_21,CKV2_AZURE_8"
          run-terraform-destroy: "true"
          run-terraform-plan-only: "false"
          terraform-version: "1.3.9"


